---
- hosts: "all"
  tasks:
    - name: Create directory
      file:
        path: /Users/nikmys/Documents/jenkins_folder
        state: directory
        mode: 0777

    - name: Run Docker container
      docker_container:
        name: nikmy_jenkins
        image: jenkins/jenkins:lts
        ports:
          - 8080:8080
        volumes:
          - /Users/nikmys/Documents/jenkins_folder:/var/jenkins_home:rw
          - /var/run/docker.sock:/var/run/docker.sock
          - /usr/bin/docker:/usr/bin/docker